builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/tsub/s3-edit/cmd.Version={{.Version}}

archives:
  - replacements:
      darwin: darwin
      linux: linux
      386: "386"
      amd64: amd64

checksum:
  name_template: 'SHASUMS'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  - tap:
      owner: tsub
      name: homebrew-s3-edit
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    description: "Edit directly a file on Amazon S3 in CLI"
    homepage: "https://github.com/tsub/s3-edit"
    install: |
      bin.install 's3-edit'
